{
 "title": "Flask Metrics Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Successful POST Requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{app=\"twitter-middleware\",method=\"POST\",status=\"200\"}"
    }
   ]
  },
  {
   "title": "Successful GET Requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{app=\"twitter-middleware\",method=\"GET\",status=\"200\"}"
    }
   ]
  },
  {
   "title": "Unsuccessful POST Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{app=\"twitter-middleware\",method=\"POST\",status=\"400\"}"
    }
   ]
  },
  {
   "title": "Unsuccessful GET Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{app=\"twitter-middleware\",method=\"GET\",status=\"404\"}"
    }
   ]
  }
 ]
}